sudo: false
language: node_js
dist: trusty
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test -- --coverage && cat ./coverage/lcov.info | npx coveralls
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version") sonar-scanner -X -Dsonar.projectVersion=$PACKAGE_VERSION
addons:
  sonarcloud:
    organization: "jmather-github"
    token:
      secure: "cEBGJ/ZYmgzF2KLd2jZs6xorrUiwfl3GZeJU1RADgezgrGLWduBp47uonHUdsm+FY5gDcrXj4ELhBRx52oaKxvGJSvRCco9o76NEoAhxbAV7hKvRYFcnlfFUVQ44bQoLWRzF9+fXBPyL5ZyJrVaHofYoPuyDKhBBG2XNvRKJ5sFriRfKEW+Q1mLPZIpK0IZ9lLfoJZpO8GyhLUf3NZu9910IAJnqUt8AWLF/dHpc/dlV8dvwF8P0xoOEoQsLV6gLlDu6VpLE9FbCsTUcMHQL6S8l7gjZAKNPT7zIWzokxoQTnbUfGEGjMTEn0hebtKXMw5CsUxxZe011vY3tAJinHBOsQoJMCh/EGjvw4ifqr2glkcz68LgjfCbybN20jKbp8Gipaurr4+WrEKvIqiB9FM06fqHeUDUqrNRatz/uXfl8Nzlx7+2zJiKa3QFC343PShDw+8WqOp5+H+VxhMY8EN9MTKA+61RMB5qSCvn9B65DqEg9R9+abkryxT05nQ04+0V71+2ckCi/EDOUytGp1eR+rHev7IrkrfkG4WPznnetSS1hHeyztJ0kNEbZfeKxtx8n467E4jiQ8f1daZAfiWkOOa8j3Dua1osPTWDgxnip0HRD7SICVHQZb8gG/X2kCZko+2WnIlZp+Z05japtaghZo1euoX6lg21BWtayVfU="