orm:
  singular: Deployment Target
  plural: Deployment Targets
  relations:
    - local_property: component
      joins:
        - schema: component.schema.yaml
          local_key: component_name
          foreign_key: name
          type: one
    - local_property: server
      joins:
        - schema: server.schema.yaml
          local_key: server_name
          foreign_key: name
          type: one
    - local_property: domain
      joins:
        - schema: domain.schema.yaml
          local_key: domain_name
          foreign_key: name
          type: one
type: object
properties:
  name:
    type: string
  component_name:
    type: string
  domain_name:
    type: string
  server_name:
    type: string
  environment_name:
    type: string
  path:
    type: string
    default: /
additionalProperties: false