orm:
  singular: Environment Component
  plural: Environment Components
  relations:
    - local_property: component
      joins:
        - type: one
          schema: component.schema.yaml
          local_key: component_name
          foreign_key: name
    - local_property: environment
      joins:
        - type: one
          schema: environment.schema.yaml
          local_key: environment_name
          foreign_key: name
    - local_property: server
      joins:
        - type: one
          schema: server.schema.yaml
          local_key: server_name
          foreign_key: name
    - local_property: domain
      joins:
        - type: one
          schema: domain.schema.yaml
          local_key: domain_name
          foreign_key: name
type: object
properties:
  name:
    type: string
    expression: this.environment_name + ' ' + this.component_name + ' ' + this.deployment_target
  environment_name:
    type: string
  component_name:
    type: string
  url:
    type: string
  domain_name:
    type: string
    expression: this.url.split('://')[1].split('/')[0].split(':')[0]
  server_name:
    type: string
  deployment_target:
    type: string
    expression: this.url || this.server_name